// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package fi.opendemocracy.domain;

import fi.opendemocracy.domain.ODUserDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ODUserIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ODUserIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ODUserIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: ODUserIntegrationTest: @Transactional;
    
    @Autowired
    private ODUserDataOnDemand ODUserIntegrationTest.dod;
    
    @Test
    public void ODUserIntegrationTest.testCountODUsers() {
        org.junit.Assert.assertNotNull("Data on demand for 'ODUser' failed to initialize correctly", dod.getRandomODUser());
        long count = fi.opendemocracy.domain.ODUser.countODUsers();
        org.junit.Assert.assertTrue("Counter for 'ODUser' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ODUserIntegrationTest.testFindODUser() {
        fi.opendemocracy.domain.ODUser obj = dod.getRandomODUser();
        org.junit.Assert.assertNotNull("Data on demand for 'ODUser' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'ODUser' failed to provide an identifier", id);
        obj = fi.opendemocracy.domain.ODUser.findODUser(id);
        org.junit.Assert.assertNotNull("Find method for 'ODUser' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'ODUser' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ODUserIntegrationTest.testFindAllODUsers() {
        org.junit.Assert.assertNotNull("Data on demand for 'ODUser' failed to initialize correctly", dod.getRandomODUser());
        long count = fi.opendemocracy.domain.ODUser.countODUsers();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'ODUser', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<fi.opendemocracy.domain.ODUser> result = fi.opendemocracy.domain.ODUser.findAllODUsers();
        org.junit.Assert.assertNotNull("Find all method for 'ODUser' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'ODUser' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ODUserIntegrationTest.testFindODUserEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'ODUser' failed to initialize correctly", dod.getRandomODUser());
        long count = fi.opendemocracy.domain.ODUser.countODUsers();
        if (count > 20) count = 20;
        java.util.List<fi.opendemocracy.domain.ODUser> result = fi.opendemocracy.domain.ODUser.findODUserEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'ODUser' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'ODUser' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ODUserIntegrationTest.testFlush() {
        fi.opendemocracy.domain.ODUser obj = dod.getRandomODUser();
        org.junit.Assert.assertNotNull("Data on demand for 'ODUser' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'ODUser' failed to provide an identifier", id);
        obj = fi.opendemocracy.domain.ODUser.findODUser(id);
        org.junit.Assert.assertNotNull("Find method for 'ODUser' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyODUser(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'ODUser' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ODUserIntegrationTest.testMerge() {
        fi.opendemocracy.domain.ODUser obj = dod.getRandomODUser();
        org.junit.Assert.assertNotNull("Data on demand for 'ODUser' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'ODUser' failed to provide an identifier", id);
        obj = fi.opendemocracy.domain.ODUser.findODUser(id);
        boolean modified =  dod.modifyODUser(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        fi.opendemocracy.domain.ODUser merged =  obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'ODUser' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ODUserIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'ODUser' failed to initialize correctly", dod.getRandomODUser());
        fi.opendemocracy.domain.ODUser obj = dod.getNewTransientODUser(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'ODUser' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'ODUser' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'ODUser' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ODUserIntegrationTest.testRemove() {
        fi.opendemocracy.domain.ODUser obj = dod.getRandomODUser();
        org.junit.Assert.assertNotNull("Data on demand for 'ODUser' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'ODUser' failed to provide an identifier", id);
        obj = fi.opendemocracy.domain.ODUser.findODUser(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'ODUser' with identifier '" + id + "'", fi.opendemocracy.domain.ODUser.findODUser(id));
    }
    
}
