package com.opendemocracy.voting.ui;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Label;
import com.vaadin.ui.NativeSelect;
import com.vaadin.ui.RichTextArea;

public class Categories extends CustomComponent {

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private RichTextArea richTextArea_1;
	@AutoGenerated
	private NativeSelect languageSelect;
	@AutoGenerated
	private Label categoryLabel;
	@AutoGenerated
	private Button button_1;
	@AutoGenerated
	private ComboBox categoryComboBox;

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public Categories() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// categoryComboBox
		categoryComboBox = new ComboBox();
		categoryComboBox.setImmediate(false);
		categoryComboBox.setDescription("Category name");
		categoryComboBox.setWidth("-1px");
		categoryComboBox.setHeight("-1px");
		mainLayout.addComponent(categoryComboBox, "top:80.0px;left:40.0px;");
		
		// button_1
		button_1 = new Button();
		button_1.setCaption("Button");
		button_1.setImmediate(true);
		button_1.setWidth("-1px");
		button_1.setHeight("-1px");
		mainLayout.addComponent(button_1, "top:340.0px;left:40.0px;");
		
		// categoryLabel
		categoryLabel = new Label();
		categoryLabel.setImmediate(false);
		categoryLabel.setWidth("-1px");
		categoryLabel.setHeight("-1px");
		categoryLabel.setValue("New category");
		mainLayout.addComponent(categoryLabel, "top:42.0px;left:40.0px;");
		
		// languageSelect
		languageSelect = new NativeSelect();
		languageSelect.setImmediate(false);
		languageSelect.setDescription("Language");
		languageSelect.setWidth("-1px");
		languageSelect.setHeight("-1px");
		mainLayout.addComponent(languageSelect, "top:78.0px;left:236.0px;");
		
		// richTextArea_1
		richTextArea_1 = new RichTextArea();
		richTextArea_1.setImmediate(false);
		richTextArea_1.setWidth("-1px");
		richTextArea_1.setHeight("-1px");
		mainLayout.addComponent(richTextArea_1, "top:120.0px;left:40.0px;");
		
		return mainLayout;
	}

}
