package com.opendemocracy.voting.ui;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Label;
import com.vaadin.ui.Slider;

public class Experts extends CustomComponent {

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private Label label_1;
	@AutoGenerated
	private Button button_2;
	@AutoGenerated
	private Button submitButton;
	@AutoGenerated
	private Label noOpinionLabel;
	@AutoGenerated
	private Label distrustLabel;
	@AutoGenerated
	private Label trustLabel;
	@AutoGenerated
	private Slider slider_2;
	@AutoGenerated
	private ModalWindow ExpertRepresentation;

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public Experts() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// ExpertRepresentation
		ExpertRepresentation = new ModalWindow();
		ExpertRepresentation.setCaption("Representative trust");
		ExpertRepresentation.setImmediate(false);
		ExpertRepresentation
				.setDescription("Choose represenativity of expert in category");
		ExpertRepresentation.setWidth("573px");
		ExpertRepresentation.setHeight("280px");
		mainLayout.addComponent(ExpertRepresentation, "left:0.0px;");
		
		// slider_2
		slider_2 = new Slider();
		slider_2.setImmediate(false);
		slider_2.setWidth("296px");
		slider_2.setHeight("-1px");
		mainLayout.addComponent(slider_2, "top:46.0px;left:127.0px;");
		
		// trustLabel
		trustLabel = new Label();
		trustLabel.setImmediate(false);
		trustLabel.setWidth("40px");
		trustLabel.setHeight("-1px");
		trustLabel.setValue("Trust");
		mainLayout.addComponent(trustLabel, "top:44.0px;left:84.0px;");
		
		// distrustLabel
		distrustLabel = new Label();
		distrustLabel.setImmediate(false);
		distrustLabel.setWidth("-1px");
		distrustLabel.setHeight("-1px");
		distrustLabel.setValue("Distrust");
		mainLayout.addComponent(distrustLabel, "top:44.0px;left:435.0px;");
		
		// noOpinionLabel
		noOpinionLabel = new Label();
		noOpinionLabel.setImmediate(false);
		noOpinionLabel.setWidth("-1px");
		noOpinionLabel.setHeight("-1px");
		noOpinionLabel.setValue("No experience");
		mainLayout.addComponent(noOpinionLabel, "top:20.0px;left:232.0px;");
		
		// submitButton
		submitButton = new Button();
		submitButton.setCaption("Save");
		submitButton.setImmediate(true);
		submitButton.setWidth("100.0%");
		submitButton.setHeight("-1px");
		mainLayout.addComponent(submitButton,
				"top:200.0px;right:926.0px;left:124.0px;");
		
		// button_2
		button_2 = new Button();
		button_2.setCaption("Remove");
		button_2.setImmediate(true);
		button_2.setWidth("75px");
		button_2.setHeight("-1px");
		mainLayout.addComponent(button_2, "top:200.0px;right:700.0px;");
		
		// label_1
		label_1 = new Label();
		label_1.setImmediate(false);
		label_1.setWidth("-1px");
		label_1.setHeight("-1px");
		label_1.setValue("Do you trust user: UserName as an representative in category CategoryName");
		mainLayout.addComponent(label_1, "top:120.0px;left:72.0px;");
		
		return mainLayout;
	}

}
