package fi.opendemocracy.voting.web;

import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Map;

import org.junit.experimental.categories.Categories;
import org.vaadin.navigator.Navigator;

import com.vaadin.Application;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.util.MethodProperty;
import com.vaadin.spring.roo.addon.annotations.RooVaadinEntityManagerView;
import com.vaadin.spring.roo.addon.annotations.RooVaadinEntityView;
import com.vaadin.terminal.Sizeable;
import com.vaadin.terminal.ThemeResource;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.Button.ClickListener;
import com.vaadin.ui.CheckBox;
import com.vaadin.ui.Component;
import com.vaadin.ui.CssLayout;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Embedded;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.HorizontalSplitPanel;
import com.vaadin.ui.Label;
import com.vaadin.ui.NativeButton;
import com.vaadin.ui.Panel;
import com.vaadin.ui.TabSheet;
import com.vaadin.ui.TabSheet.SelectedTabChangeEvent;
import com.vaadin.ui.TabSheet.Tab;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.themes.Reindeer;

import fi.opendemocracy.voting.domain.Category;
import fi.opendemocracy.voting.web.ui.CategoryView;
import fi.opendemocracy.voting.web.ui.PropositionView;

/**
 * Entity manager view that by default automatically discovers all entity views
 * (classes with the {@link RooVaadinEntityView} annotation) and lets the user
 * choose one of them to display.
 *
 * An entity view must implement the {@link Navigator.View} interface to be
 * automatically added to the view list. Other views can be registered by
 * calling <code>navigator.addView()</code> and added to the sidebar menu by
 * adding a corresponding {@link SidebarItem} to <code>menuItems</code> and
 * <code>viewList</code>.
 * 
 * This class is designed to be compatible with the Vaadin Visual Editor.
 * 
 * All methods and fields not marked with the {@link AutoGenerated} annotation
 * can be modified freely.
 * 
 * If you are planning to use the visual editor, do not touch the methods marked
 * with the {@link AutoGenerated} annotation - they will be removed and
 * re-generated when saving the class from the visual editor. Instead, add any
 * custom code to methods called from the constructor after the initial view
 * construction.
 * 
 * If you will not use the Vaadin Visual Editor to edit this class, all the
 * {@link AutoGenerated} annotations can be removed.
 */
@RooVaadinEntityManagerView
public class OpenDemocracyVotingEntityManagerView extends CustomComponent {

	//UI objects
	private VerticalLayout mainLayout;
	private HorizontalLayout toolbar;
	private Button btnPropositions;
	private Button btnCategories;
    private TabNavigator navigator;
       
    //Construct main layout.
    public OpenDemocracyVotingEntityManagerView() {
        setSizeFull();
        // build the layout
        buildMainLayout();
        setCompositionRoot(mainLayout);
        // layout and style adjustments
        mainLayout.addStyleName("main");
        mainLayout.addStyleName(Reindeer.TABSHEET_BORDERLESS);
        // add listeners
        addListeners();
    }
    
    private void buildMainLayout() {
        // top-level component properties
        setWidth("100.0%");
        setHeight("100.0%");
        // common part: create layout
        mainLayout = new VerticalLayout();
        mainLayout.setWidth("100.0%");
        mainLayout.setHeight("100.0%");
        // add content
        buildToolbar();
        buildNavigator();
        // expand tabsheet
        mainLayout.setExpandRatio(navigator, 1.0f);
    }
    
    //Construct toolbar header
	private void buildToolbar() {
		toolbar = new HorizontalLayout();
		//layout constants
		Embedded logo = new Embedded("", ThemeConstants.LOGO);
		//buttons
		btnPropositions = new Button("Propositions");
		btnCategories = new Button("Categories");
		btnPropositions.setIcon(ThemeConstants.TOOLBAR_ICON_PROPOSITION);
		btnCategories.setIcon(ThemeConstants.TOOLBAR_ICON_CATEGORIES);
		//add components
		toolbar.addComponent(btnPropositions);
		toolbar.addComponent(btnCategories);
		toolbar.addComponent(logo);
		//properties
		toolbar.setMargin(true);
		toolbar.setSpacing(true);
		toolbar.setStyleName("toolbar");
		toolbar.setWidth("100%");
		toolbar.setHeight(90, Sizeable.UNITS_PIXELS);
		toolbar.setComponentAlignment(logo, Alignment.MIDDLE_RIGHT);
		toolbar.setExpandRatio(logo, 1.0f);
		//add toolbar to layout
        mainLayout.addComponent(toolbar);
	}
    
    // initialize navigator
    private void buildNavigator(){
        navigator = new TabNavigator();
        navigator.setSizeFull();
        navigator.setImmediate(false);
        navigator.addView("home", HomeView.class, true);
    	navigator.addView("category", CategoryView.class);
    	navigator.addView("proposition", PropositionView.class);
        mainLayout.addComponent(navigator);
    }
        
    // add listeners
    private void addListeners(){
    	btnCategories.addListener(new Button.ClickListener() {
            public void buttonClick(ClickEvent event) {
            	navigator.navigateTo("category");
            }
        });
    	btnPropositions.addListener(new Button.ClickListener() {
            public void buttonClick(ClickEvent event) {
            	navigator.navigateTo("proposition");
            }
        });
    }
    
    //Home view
    public static class HomeView extends VerticalLayout implements TabNavigator.View {
        public HomeView() {
        	setCaption(ThemeConstants.TAB_CAPTION_HOME);
        	setIcon(ThemeConstants.TAB_ICON_HOME);
    		setMargin(true);
    		setSizeFull();
    		addStyleName(Reindeer.LAYOUT_WHITE);
            Label l = new Label(
                    "<h1 class=\"v-label-h1\" style=\"text-align: center;\">Welcome to OpenDemocracy Alpha</h1> Select an option above to begin",
                    Label.CONTENT_XHTML);
            l.setSizeUndefined();
            l.addStyleName(Reindeer.LABEL_SMALL);
            addComponent(l);
            setComponentAlignment(l, Alignment.MIDDLE_CENTER);
        	setReadOnly(true);
        }
        //Unused interfaces
        public void init(TabNavigator navigator, Application application) {}
        public void navigateTo(String requestedDataId) {}
        public String getWarningForNavigatingFrom() {return null;}
    }
}