// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package fi.opendemocracy.voting.domain;

import fi.opendemocracy.voting.domain.ODUser;
import java.lang.String;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect ODUserDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ODUserDataOnDemand: @Component;
    
    private Random ODUserDataOnDemand.rnd = new SecureRandom();
    
    private List<ODUser> ODUserDataOnDemand.data;
    
    public ODUser ODUserDataOnDemand.getNewTransientODUser(int index) {
        ODUser obj = new ODUser();
        setAdmin(obj, index);
        setName(obj, index);
        setPassword(obj, index);
        return obj;
    }
    
    public void ODUserDataOnDemand.setAdmin(ODUser obj, int index) {
        Boolean admin = true;
        obj.setAdmin(admin);
    }
    
    public void ODUserDataOnDemand.setName(ODUser obj, int index) {
        String name = "name_" + index;
        obj.setName(name);
    }
    
    public void ODUserDataOnDemand.setPassword(ODUser obj, int index) {
        String password = "password_" + index;
        obj.setPassword(password);
    }
    
    public ODUser ODUserDataOnDemand.getSpecificODUser(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        ODUser obj = data.get(index);
        return ODUser.findODUser(obj.getId());
    }
    
    public ODUser ODUserDataOnDemand.getRandomODUser() {
        init();
        ODUser obj = data.get(rnd.nextInt(data.size()));
        return ODUser.findODUser(obj.getId());
    }
    
    public boolean ODUserDataOnDemand.modifyODUser(ODUser obj) {
        return false;
    }
    
    public void ODUserDataOnDemand.init() {
        data = ODUser.findODUserEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'ODUser' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<fi.opendemocracy.voting.domain.ODUser>();
        for (int i = 0; i < 10; i++) {
            ODUser obj = getNewTransientODUser(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> it = e.getConstraintViolations().iterator(); it.hasNext();) {
                    ConstraintViolation<?> cv = it.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
