// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package fi.opendemocracy.voting.domain;

import fi.opendemocracy.voting.domain.PropositionDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect PropositionIntegrationTest_Roo_IntegrationTest {
    
    declare @type: PropositionIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: PropositionIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: PropositionIntegrationTest: @Transactional;
    
    @Autowired
    private PropositionDataOnDemand PropositionIntegrationTest.dod;
    
    @Test
    public void PropositionIntegrationTest.testCountPropositions() {
        org.junit.Assert.assertNotNull("Data on demand for 'Proposition' failed to initialize correctly", dod.getRandomProposition());
        long count = fi.opendemocracy.voting.domain.Proposition.countPropositions();
        org.junit.Assert.assertTrue("Counter for 'Proposition' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void PropositionIntegrationTest.testFindProposition() {
        fi.opendemocracy.voting.domain.Proposition obj = dod.getRandomProposition();
        org.junit.Assert.assertNotNull("Data on demand for 'Proposition' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Proposition' failed to provide an identifier", id);
        obj = fi.opendemocracy.voting.domain.Proposition.findProposition(id);
        org.junit.Assert.assertNotNull("Find method for 'Proposition' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'Proposition' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void PropositionIntegrationTest.testFindAllPropositions() {
        org.junit.Assert.assertNotNull("Data on demand for 'Proposition' failed to initialize correctly", dod.getRandomProposition());
        long count = fi.opendemocracy.voting.domain.Proposition.countPropositions();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'Proposition', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<fi.opendemocracy.voting.domain.Proposition> result = fi.opendemocracy.voting.domain.Proposition.findAllPropositions();
        org.junit.Assert.assertNotNull("Find all method for 'Proposition' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'Proposition' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void PropositionIntegrationTest.testFindPropositionEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'Proposition' failed to initialize correctly", dod.getRandomProposition());
        long count = fi.opendemocracy.voting.domain.Proposition.countPropositions();
        if (count > 20) count = 20;
        java.util.List<fi.opendemocracy.voting.domain.Proposition> result = fi.opendemocracy.voting.domain.Proposition.findPropositionEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'Proposition' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'Proposition' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void PropositionIntegrationTest.testFlush() {
        fi.opendemocracy.voting.domain.Proposition obj = dod.getRandomProposition();
        org.junit.Assert.assertNotNull("Data on demand for 'Proposition' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Proposition' failed to provide an identifier", id);
        obj = fi.opendemocracy.voting.domain.Proposition.findProposition(id);
        org.junit.Assert.assertNotNull("Find method for 'Proposition' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyProposition(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'Proposition' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PropositionIntegrationTest.testMerge() {
        fi.opendemocracy.voting.domain.Proposition obj = dod.getRandomProposition();
        org.junit.Assert.assertNotNull("Data on demand for 'Proposition' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Proposition' failed to provide an identifier", id);
        obj = fi.opendemocracy.voting.domain.Proposition.findProposition(id);
        boolean modified =  dod.modifyProposition(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        fi.opendemocracy.voting.domain.Proposition merged =  obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'Proposition' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PropositionIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'Proposition' failed to initialize correctly", dod.getRandomProposition());
        fi.opendemocracy.voting.domain.Proposition obj = dod.getNewTransientProposition(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'Proposition' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'Proposition' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'Proposition' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void PropositionIntegrationTest.testRemove() {
        fi.opendemocracy.voting.domain.Proposition obj = dod.getRandomProposition();
        org.junit.Assert.assertNotNull("Data on demand for 'Proposition' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Proposition' failed to provide an identifier", id);
        obj = fi.opendemocracy.voting.domain.Proposition.findProposition(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'Proposition' with identifier '" + id + "'", fi.opendemocracy.voting.domain.Proposition.findProposition(id));
    }
    
}
