package fi.opendemocracy.web;

import java.util.EnumSet;
import java.util.Map;
import java.util.Set;

import org.vaadin.navigator.Navigator;
import org.vaadin.openid.OpenIdHandler;
import org.vaadin.openid.OpenIdHandler.UserAttribute;

import com.vaadin.Application;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.Link;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Window;

public class OpenIDView extends CustomComponent implements Navigator.View {
	@AutoGenerated
	private VerticalLayout mainLayout;


	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */


	


	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */


	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	Application application;
	Navigator navigator;

	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public OpenIDView() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}
	

	private void addLogin() {
	    final VerticalLayout container = new VerticalLayout();
	    container.setSpacing(true);
	    container.setMargin(true);
	
	    mainLayout.addComponent(container);
	
	    final OpenIdHandler openIdHandler = new OpenIdHandler(application);
	    openIdHandler.setRequestedAttributes(UserAttribute.values());
	
	    final HorizontalLayout linkHolder = new HorizontalLayout();
	    linkHolder.setSpacing(true);
	    linkHolder
	            .addComponent(createLoginLink(openIdHandler,
	                    "https://www.google.com/accounts/o8/id",
	                    "Log in using Google"));
	    linkHolder.addComponent(createLoginLink(openIdHandler,
	            "https://me.yahoo.com", "Log in using Yahoo"));
	    
	    container.addComponent(linkHolder);
	
	    openIdHandler.addListener(new OpenIdHandler.OpenIdLoginListener() {
	        public void onLogin(String id, Map<UserAttribute, String> userInfo) {
	            container.removeComponent(linkHolder);
	            container.addComponent(new Label("Logged in identity: " + id));
	            Set<UserAttribute> missingFields = EnumSet
	                    .allOf(UserAttribute.class);
	            for (UserAttribute field : userInfo.keySet()) {
	            	container.addComponent(new Label(field + ": "
	                        + userInfo.get(field)));
	                missingFields.remove(field);
	            }
	            for (UserAttribute registrationFields : missingFields) {
	            	container.addComponent(new Label(registrationFields
	                        + " not provided"));
	            }
	
	            openIdHandler.close();
	        }
	
	        public void onCancel() {
	            application.getMainWindow().removeComponent(linkHolder);
	            application.getMainWindow().addComponent(
	                    new Label("Too sad you didn't want to log in."));
	
	            openIdHandler.close();
	        }
	    });
	}


    private static Link createLoginLink(OpenIdHandler openIdHandler, String id,
            String caption) {
        return new Link(caption, openIdHandler.getLoginResource(id),
                "openidLogin", 600, 400, Window.BORDER_NONE);
    }

	@Override
	public void init(Navigator navigator, Application application) {
		this.application = application;
		this.navigator = navigator;
		addLogin();
	}

	@Override
	public void navigateTo(String requestedDataId) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public String getWarningForNavigatingFrom() {
		// TODO Auto-generated method stub
		return null;
	}


	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		return mainLayout;
	}

}
