// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package fi.opendemocracy.domain;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;

import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect ExpertDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ExpertDataOnDemand: @Component;
    
    private Random ExpertDataOnDemand.rnd = new SecureRandom();
    
    private List<Expert> ExpertDataOnDemand.data;
    
    @Autowired
    private CategoryDataOnDemand ExpertDataOnDemand.categoryDataOnDemand;
    
    public Expert ExpertDataOnDemand.getNewTransientExpert(int index) {
        Expert obj = new Expert();
        setCategory(obj, index);
        setExpertise(obj, index);
        setOdUser(obj, index);
        setTs(obj, index);
        return obj;
    }
    
    public void ExpertDataOnDemand.setCategory(Expert obj, int index) {
        Category category = categoryDataOnDemand.getRandomCategory();
        obj.setCategory(category);
    }
    
    public void ExpertDataOnDemand.setExpertise(Expert obj, int index) {
        String expertise = "expertise_" + index;
        obj.setExpertise(expertise);
    }
    
    public void ExpertDataOnDemand.setOdUser(Expert obj, int index) {
        ODUser odUser = null;
        obj.setOdUser(odUser);
    }
    
    public void ExpertDataOnDemand.setTs(Expert obj, int index) {
        Date ts = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setTs(ts);
    }
    
    public Expert ExpertDataOnDemand.getSpecificExpert(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        Expert obj = data.get(index);
        return Expert.findExpert(obj.getId());
    }
    
    public Expert ExpertDataOnDemand.getRandomExpert() {
        init();
        Expert obj = data.get(rnd.nextInt(data.size()));
        return Expert.findExpert(obj.getId());
    }
    
    public boolean ExpertDataOnDemand.modifyExpert(Expert obj) {
        return false;
    }
    
    public void ExpertDataOnDemand.init() {
        data = Expert.findExpertEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'Expert' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<fi.opendemocracy.domain.Expert>();
        for (int i = 0; i < 10; i++) {
            Expert obj = getNewTransientExpert(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> it = e.getConstraintViolations().iterator(); it.hasNext();) {
                    ConstraintViolation<?> cv = it.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
