// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package fi.opendemocracy.domain;

import fi.opendemocracy.domain.Expert;
import fi.opendemocracy.domain.ExpertDataOnDemand;
import fi.opendemocracy.domain.ExpertIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ExpertIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ExpertIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ExpertIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ExpertIntegrationTest: @Transactional;
    
    @Autowired
    private ExpertDataOnDemand ExpertIntegrationTest.dod;
    
    @Test
    public void ExpertIntegrationTest.testCountExperts() {
        Assert.assertNotNull("Data on demand for 'Expert' failed to initialize correctly", dod.getRandomExpert());
        long count = Expert.countExperts();
        Assert.assertTrue("Counter for 'Expert' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ExpertIntegrationTest.testFindExpert() {
        Expert obj = dod.getRandomExpert();
        Assert.assertNotNull("Data on demand for 'Expert' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Expert' failed to provide an identifier", id);
        obj = Expert.findExpert(id);
        Assert.assertNotNull("Find method for 'Expert' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Expert' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ExpertIntegrationTest.testFindAllExperts() {
        Assert.assertNotNull("Data on demand for 'Expert' failed to initialize correctly", dod.getRandomExpert());
        long count = Expert.countExperts();
        Assert.assertTrue("Too expensive to perform a find all test for 'Expert', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Expert> result = Expert.findAllExperts();
        Assert.assertNotNull("Find all method for 'Expert' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Expert' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ExpertIntegrationTest.testFindExpertEntries() {
        Assert.assertNotNull("Data on demand for 'Expert' failed to initialize correctly", dod.getRandomExpert());
        long count = Expert.countExperts();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Expert> result = Expert.findExpertEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Expert' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Expert' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ExpertIntegrationTest.testFlush() {
        Expert obj = dod.getRandomExpert();
        Assert.assertNotNull("Data on demand for 'Expert' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Expert' failed to provide an identifier", id);
        obj = Expert.findExpert(id);
        Assert.assertNotNull("Find method for 'Expert' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyExpert(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Expert' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ExpertIntegrationTest.testMergeUpdate() {
        Expert obj = dod.getRandomExpert();
        Assert.assertNotNull("Data on demand for 'Expert' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Expert' failed to provide an identifier", id);
        obj = Expert.findExpert(id);
        boolean modified =  dod.modifyExpert(obj);
        Integer currentVersion = obj.getVersion();
        Expert merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Expert' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ExpertIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Expert' failed to initialize correctly", dod.getRandomExpert());
        Expert obj = dod.getNewTransientExpert(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Expert' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Expert' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Expert' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ExpertIntegrationTest.testRemove() {
        Expert obj = dod.getRandomExpert();
        Assert.assertNotNull("Data on demand for 'Expert' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Expert' failed to provide an identifier", id);
        obj = Expert.findExpert(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Expert' with identifier '" + id + "'", Expert.findExpert(id));
    }
    
}
