// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package fi.opendemocracy.domain;

import fi.opendemocracy.domain.ODUser;
import fi.opendemocracy.domain.ODUserDataOnDemand;
import fi.opendemocracy.domain.Proposition;
import java.lang.String;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect PropositionDataOnDemand_Roo_DataOnDemand {
    
    declare @type: PropositionDataOnDemand: @Component;
    
    private Random PropositionDataOnDemand.rnd = new SecureRandom();
    
    private List<Proposition> PropositionDataOnDemand.data;
    
    @Autowired
    private ODUserDataOnDemand PropositionDataOnDemand.oDUserDataOnDemand;
    
    public Proposition PropositionDataOnDemand.getNewTransientProposition(int index) {
        Proposition obj = new Proposition();
        setAuthor(obj, index);
        setDescription(obj, index);
        setTitle(obj, index);
        return obj;
    }
    
    public void PropositionDataOnDemand.setAuthor(Proposition obj, int index) {
        ODUser author = oDUserDataOnDemand.getRandomODUser();
        obj.setAuthor(author);
    }
    
    public void PropositionDataOnDemand.setDescription(Proposition obj, int index) {
        String description = "description_" + index;
        if (description.length() > 4096) {
            description = description.substring(0, 4096);
        }
        obj.setDescription(description);
    }
    
    public void PropositionDataOnDemand.setTitle(Proposition obj, int index) {
        String title = "title_" + index;
        if (title.length() > 255) {
            title = title.substring(0, 255);
        }
        obj.setTitle(title);
    }
    
    public Proposition PropositionDataOnDemand.getSpecificProposition(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        Proposition obj = data.get(index);
        return Proposition.findProposition(obj.getId());
    }
    
    public Proposition PropositionDataOnDemand.getRandomProposition() {
        init();
        Proposition obj = data.get(rnd.nextInt(data.size()));
        return Proposition.findProposition(obj.getId());
    }
    
    public boolean PropositionDataOnDemand.modifyProposition(Proposition obj) {
        return false;
    }
    
    public void PropositionDataOnDemand.init() {
        data = Proposition.findPropositionEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'Proposition' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<fi.opendemocracy.domain.Proposition>();
        for (int i = 0; i < 10; i++) {
            Proposition obj = getNewTransientProposition(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> it = e.getConstraintViolations().iterator(); it.hasNext();) {
                    ConstraintViolation<?> cv = it.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
