// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package fi.opendemocracy.domain;

import fi.opendemocracy.domain.PropositionOptionDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect PropositionOptionIntegrationTest_Roo_IntegrationTest {
    
    declare @type: PropositionOptionIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: PropositionOptionIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: PropositionOptionIntegrationTest: @Transactional;
    
    @Autowired
    private PropositionOptionDataOnDemand PropositionOptionIntegrationTest.dod;
    
    @Test
    public void PropositionOptionIntegrationTest.testCountPropositionOptions() {
        org.junit.Assert.assertNotNull("Data on demand for 'PropositionOption' failed to initialize correctly", dod.getRandomPropositionOption());
        long count = fi.opendemocracy.domain.PropositionOption.countPropositionOptions();
        org.junit.Assert.assertTrue("Counter for 'PropositionOption' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void PropositionOptionIntegrationTest.testFindPropositionOption() {
        fi.opendemocracy.domain.PropositionOption obj = dod.getRandomPropositionOption();
        org.junit.Assert.assertNotNull("Data on demand for 'PropositionOption' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'PropositionOption' failed to provide an identifier", id);
        obj = fi.opendemocracy.domain.PropositionOption.findPropositionOption(id);
        org.junit.Assert.assertNotNull("Find method for 'PropositionOption' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'PropositionOption' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void PropositionOptionIntegrationTest.testFindAllPropositionOptions() {
        org.junit.Assert.assertNotNull("Data on demand for 'PropositionOption' failed to initialize correctly", dod.getRandomPropositionOption());
        long count = fi.opendemocracy.domain.PropositionOption.countPropositionOptions();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'PropositionOption', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<fi.opendemocracy.domain.PropositionOption> result = fi.opendemocracy.domain.PropositionOption.findAllPropositionOptions();
        org.junit.Assert.assertNotNull("Find all method for 'PropositionOption' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'PropositionOption' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void PropositionOptionIntegrationTest.testFindPropositionOptionEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'PropositionOption' failed to initialize correctly", dod.getRandomPropositionOption());
        long count = fi.opendemocracy.domain.PropositionOption.countPropositionOptions();
        if (count > 20) count = 20;
        java.util.List<fi.opendemocracy.domain.PropositionOption> result = fi.opendemocracy.domain.PropositionOption.findPropositionOptionEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'PropositionOption' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'PropositionOption' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void PropositionOptionIntegrationTest.testFlush() {
        fi.opendemocracy.domain.PropositionOption obj = dod.getRandomPropositionOption();
        org.junit.Assert.assertNotNull("Data on demand for 'PropositionOption' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'PropositionOption' failed to provide an identifier", id);
        obj = fi.opendemocracy.domain.PropositionOption.findPropositionOption(id);
        org.junit.Assert.assertNotNull("Find method for 'PropositionOption' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyPropositionOption(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'PropositionOption' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PropositionOptionIntegrationTest.testMerge() {
        fi.opendemocracy.domain.PropositionOption obj = dod.getRandomPropositionOption();
        org.junit.Assert.assertNotNull("Data on demand for 'PropositionOption' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'PropositionOption' failed to provide an identifier", id);
        obj = fi.opendemocracy.domain.PropositionOption.findPropositionOption(id);
        boolean modified =  dod.modifyPropositionOption(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        fi.opendemocracy.domain.PropositionOption merged =  obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'PropositionOption' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PropositionOptionIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'PropositionOption' failed to initialize correctly", dod.getRandomPropositionOption());
        fi.opendemocracy.domain.PropositionOption obj = dod.getNewTransientPropositionOption(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'PropositionOption' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'PropositionOption' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'PropositionOption' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void PropositionOptionIntegrationTest.testRemove() {
        fi.opendemocracy.domain.PropositionOption obj = dod.getRandomPropositionOption();
        org.junit.Assert.assertNotNull("Data on demand for 'PropositionOption' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'PropositionOption' failed to provide an identifier", id);
        obj = fi.opendemocracy.domain.PropositionOption.findPropositionOption(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'PropositionOption' with identifier '" + id + "'", fi.opendemocracy.domain.PropositionOption.findPropositionOption(id));
    }
    
}
