// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package fi.opendemocracy.domain;

import fi.opendemocracy.domain.PropositionOptionDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect PropositionOptionDataOnDemand_Roo_Configurable {
    
    declare @type: PropositionOptionDataOnDemand: @Configurable;
    
}
