// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package fi.opendemocracy.domain;

import fi.opendemocracy.domain.PropositionOption;
import fi.opendemocracy.domain.PropositionOptionDataOnDemand;
import fi.opendemocracy.domain.PropositionOptionIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect PropositionOptionIntegrationTest_Roo_IntegrationTest {
    
    declare @type: PropositionOptionIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: PropositionOptionIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: PropositionOptionIntegrationTest: @Transactional;
    
    @Autowired
    private PropositionOptionDataOnDemand PropositionOptionIntegrationTest.dod;
    
    @Test
    public void PropositionOptionIntegrationTest.testCountPropositionOptions() {
        Assert.assertNotNull("Data on demand for 'PropositionOption' failed to initialize correctly", dod.getRandomPropositionOption());
        long count = PropositionOption.countPropositionOptions();
        Assert.assertTrue("Counter for 'PropositionOption' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void PropositionOptionIntegrationTest.testFindPropositionOption() {
        PropositionOption obj = dod.getRandomPropositionOption();
        Assert.assertNotNull("Data on demand for 'PropositionOption' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'PropositionOption' failed to provide an identifier", id);
        obj = PropositionOption.findPropositionOption(id);
        Assert.assertNotNull("Find method for 'PropositionOption' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'PropositionOption' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void PropositionOptionIntegrationTest.testFindAllPropositionOptions() {
        Assert.assertNotNull("Data on demand for 'PropositionOption' failed to initialize correctly", dod.getRandomPropositionOption());
        long count = PropositionOption.countPropositionOptions();
        Assert.assertTrue("Too expensive to perform a find all test for 'PropositionOption', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<PropositionOption> result = PropositionOption.findAllPropositionOptions();
        Assert.assertNotNull("Find all method for 'PropositionOption' illegally returned null", result);
        Assert.assertTrue("Find all method for 'PropositionOption' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void PropositionOptionIntegrationTest.testFindPropositionOptionEntries() {
        Assert.assertNotNull("Data on demand for 'PropositionOption' failed to initialize correctly", dod.getRandomPropositionOption());
        long count = PropositionOption.countPropositionOptions();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<PropositionOption> result = PropositionOption.findPropositionOptionEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'PropositionOption' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'PropositionOption' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void PropositionOptionIntegrationTest.testFlush() {
        PropositionOption obj = dod.getRandomPropositionOption();
        Assert.assertNotNull("Data on demand for 'PropositionOption' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'PropositionOption' failed to provide an identifier", id);
        obj = PropositionOption.findPropositionOption(id);
        Assert.assertNotNull("Find method for 'PropositionOption' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyPropositionOption(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'PropositionOption' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PropositionOptionIntegrationTest.testMergeUpdate() {
        PropositionOption obj = dod.getRandomPropositionOption();
        Assert.assertNotNull("Data on demand for 'PropositionOption' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'PropositionOption' failed to provide an identifier", id);
        obj = PropositionOption.findPropositionOption(id);
        boolean modified =  dod.modifyPropositionOption(obj);
        Integer currentVersion = obj.getVersion();
        PropositionOption merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'PropositionOption' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PropositionOptionIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'PropositionOption' failed to initialize correctly", dod.getRandomPropositionOption());
        PropositionOption obj = dod.getNewTransientPropositionOption(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'PropositionOption' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'PropositionOption' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'PropositionOption' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void PropositionOptionIntegrationTest.testRemove() {
        PropositionOption obj = dod.getRandomPropositionOption();
        Assert.assertNotNull("Data on demand for 'PropositionOption' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'PropositionOption' failed to provide an identifier", id);
        obj = PropositionOption.findPropositionOption(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'PropositionOption' with identifier '" + id + "'", PropositionOption.findPropositionOption(id));
    }
    
}
