// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package fi.opendemocracy.domain;

import fi.opendemocracy.domain.ODUser;
import fi.opendemocracy.domain.Proposition;
import fi.opendemocracy.domain.PropositionDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect PropositionDataOnDemand_Roo_DataOnDemand {
    
    declare @type: PropositionDataOnDemand: @Component;
    
    private Random PropositionDataOnDemand.rnd = new SecureRandom();
    
    private List<Proposition> PropositionDataOnDemand.data;
    
    public Proposition PropositionDataOnDemand.getNewTransientProposition(int index) {
        Proposition obj = new Proposition();
        setAuthor(obj, index);
        setDescription(obj, index);
        setName(obj, index);
        setTs(obj, index);
        return obj;
    }
    
    public void PropositionDataOnDemand.setAuthor(Proposition obj, int index) {
        ODUser author = null;
        obj.setAuthor(author);
    }
    
    public void PropositionDataOnDemand.setDescription(Proposition obj, int index) {
        String description = "description_" + index;
        obj.setDescription(description);
    }
    
    public void PropositionDataOnDemand.setName(Proposition obj, int index) {
        String name = "name_" + index;
        if (name.length() > 127) {
            name = name.substring(0, 127);
        }
        obj.setName(name);
    }
    
    public void PropositionDataOnDemand.setTs(Proposition obj, int index) {
        Date ts = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setTs(ts);
    }
    
    public Proposition PropositionDataOnDemand.getSpecificProposition(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Proposition obj = data.get(index);
        Long id = obj.getId();
        return Proposition.findProposition(id);
    }
    
    public Proposition PropositionDataOnDemand.getRandomProposition() {
        init();
        Proposition obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Proposition.findProposition(id);
    }
    
    public boolean PropositionDataOnDemand.modifyProposition(Proposition obj) {
        return false;
    }
    
    public void PropositionDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Proposition.findPropositionEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Proposition' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Proposition>();
        for (int i = 0; i < 10; i++) {
            Proposition obj = getNewTransientProposition(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
