// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package fi.opendemocracy.domain;

import fi.opendemocracy.domain.Expert;
import fi.opendemocracy.domain.ExpertDataOnDemand;
import fi.opendemocracy.domain.ODUser;
import fi.opendemocracy.domain.Representation;
import fi.opendemocracy.domain.RepresentationDataOnDemand;
import java.math.BigDecimal;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect RepresentationDataOnDemand_Roo_DataOnDemand {
    
    declare @type: RepresentationDataOnDemand: @Component;
    
    private Random RepresentationDataOnDemand.rnd = new SecureRandom();
    
    private List<Representation> RepresentationDataOnDemand.data;
    
    @Autowired
    private ExpertDataOnDemand RepresentationDataOnDemand.expertDataOnDemand;
    
    public Representation RepresentationDataOnDemand.getNewTransientRepresentation(int index) {
        Representation obj = new Representation();
        setExpert(obj, index);
        setOdUser(obj, index);
        setTrust(obj, index);
        setTs(obj, index);
        return obj;
    }
    
    public void RepresentationDataOnDemand.setExpert(Representation obj, int index) {
        Expert expert = expertDataOnDemand.getRandomExpert();
        obj.setExpert(expert);
    }
    
    public void RepresentationDataOnDemand.setOdUser(Representation obj, int index) {
        ODUser odUser = null;
        obj.setOdUser(odUser);
    }
    
    public void RepresentationDataOnDemand.setTrust(Representation obj, int index) {
        BigDecimal trust = BigDecimal.valueOf(index);
        obj.setTrust(trust);
    }
    
    public void RepresentationDataOnDemand.setTs(Representation obj, int index) {
        Date ts = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setTs(ts);
    }
    
    public Representation RepresentationDataOnDemand.getSpecificRepresentation(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Representation obj = data.get(index);
        Long id = obj.getId();
        return Representation.findRepresentation(id);
    }
    
    public Representation RepresentationDataOnDemand.getRandomRepresentation() {
        init();
        Representation obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Representation.findRepresentation(id);
    }
    
    public boolean RepresentationDataOnDemand.modifyRepresentation(Representation obj) {
        return false;
    }
    
    public void RepresentationDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Representation.findRepresentationEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Representation' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Representation>();
        for (int i = 0; i < 10; i++) {
            Representation obj = getNewTransientRepresentation(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
