// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package fi.opendemocracy.domain;

import fi.opendemocracy.domain.Representation;
import fi.opendemocracy.domain.RepresentationDataOnDemand;
import fi.opendemocracy.domain.RepresentationIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect RepresentationIntegrationTest_Roo_IntegrationTest {
    
    declare @type: RepresentationIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: RepresentationIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: RepresentationIntegrationTest: @Transactional;
    
    @Autowired
    private RepresentationDataOnDemand RepresentationIntegrationTest.dod;
    
    @Test
    public void RepresentationIntegrationTest.testCountRepresentations() {
        Assert.assertNotNull("Data on demand for 'Representation' failed to initialize correctly", dod.getRandomRepresentation());
        long count = Representation.countRepresentations();
        Assert.assertTrue("Counter for 'Representation' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void RepresentationIntegrationTest.testFindRepresentation() {
        Representation obj = dod.getRandomRepresentation();
        Assert.assertNotNull("Data on demand for 'Representation' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Representation' failed to provide an identifier", id);
        obj = Representation.findRepresentation(id);
        Assert.assertNotNull("Find method for 'Representation' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Representation' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void RepresentationIntegrationTest.testFindAllRepresentations() {
        Assert.assertNotNull("Data on demand for 'Representation' failed to initialize correctly", dod.getRandomRepresentation());
        long count = Representation.countRepresentations();
        Assert.assertTrue("Too expensive to perform a find all test for 'Representation', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Representation> result = Representation.findAllRepresentations();
        Assert.assertNotNull("Find all method for 'Representation' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Representation' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void RepresentationIntegrationTest.testFindRepresentationEntries() {
        Assert.assertNotNull("Data on demand for 'Representation' failed to initialize correctly", dod.getRandomRepresentation());
        long count = Representation.countRepresentations();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Representation> result = Representation.findRepresentationEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Representation' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Representation' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void RepresentationIntegrationTest.testFlush() {
        Representation obj = dod.getRandomRepresentation();
        Assert.assertNotNull("Data on demand for 'Representation' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Representation' failed to provide an identifier", id);
        obj = Representation.findRepresentation(id);
        Assert.assertNotNull("Find method for 'Representation' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyRepresentation(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Representation' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void RepresentationIntegrationTest.testMergeUpdate() {
        Representation obj = dod.getRandomRepresentation();
        Assert.assertNotNull("Data on demand for 'Representation' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Representation' failed to provide an identifier", id);
        obj = Representation.findRepresentation(id);
        boolean modified =  dod.modifyRepresentation(obj);
        Integer currentVersion = obj.getVersion();
        Representation merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Representation' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void RepresentationIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Representation' failed to initialize correctly", dod.getRandomRepresentation());
        Representation obj = dod.getNewTransientRepresentation(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Representation' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Representation' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Representation' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void RepresentationIntegrationTest.testRemove() {
        Representation obj = dod.getRandomRepresentation();
        Assert.assertNotNull("Data on demand for 'Representation' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Representation' failed to provide an identifier", id);
        obj = Representation.findRepresentation(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Representation' with identifier '" + id + "'", Representation.findRepresentation(id));
    }
    
}
