// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package fi.opendemocracy.domain;

import fi.opendemocracy.domain.ODUser;
import fi.opendemocracy.domain.Proposition;
import fi.opendemocracy.domain.PropositionDataOnDemand;
import fi.opendemocracy.domain.PropositionOption;
import fi.opendemocracy.domain.PropositionOptionDataOnDemand;
import fi.opendemocracy.domain.Vote;
import fi.opendemocracy.domain.VoteDataOnDemand;
import java.math.BigDecimal;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect VoteDataOnDemand_Roo_DataOnDemand {
    
    declare @type: VoteDataOnDemand: @Component;
    
    private Random VoteDataOnDemand.rnd = new SecureRandom();
    
    private List<Vote> VoteDataOnDemand.data;
    
    @Autowired
    private PropositionDataOnDemand VoteDataOnDemand.propositionDataOnDemand;
    
    @Autowired
    private PropositionOptionDataOnDemand VoteDataOnDemand.propositionOptionDataOnDemand;
    
    public Vote VoteDataOnDemand.getNewTransientVote(int index) {
        Vote obj = new Vote();
        setComment(obj, index);
        setOdUser(obj, index);
        setProposition(obj, index);
        setPropositionOption(obj, index);
        setSupport(obj, index);
        setTs(obj, index);
        return obj;
    }
    
    public void VoteDataOnDemand.setComment(Vote obj, int index) {
        String comment = "comment_" + index;
        obj.setComment(comment);
    }
    
    public void VoteDataOnDemand.setOdUser(Vote obj, int index) {
        ODUser odUser = null;
        obj.setOdUser(odUser);
    }
    
    public void VoteDataOnDemand.setProposition(Vote obj, int index) {
        Proposition proposition = propositionDataOnDemand.getRandomProposition();
        obj.setProposition(proposition);
    }
    
    public void VoteDataOnDemand.setPropositionOption(Vote obj, int index) {
        PropositionOption propositionOption = propositionOptionDataOnDemand.getRandomPropositionOption();
        obj.setPropositionOption(propositionOption);
    }
    
    public void VoteDataOnDemand.setSupport(Vote obj, int index) {
        BigDecimal support = BigDecimal.valueOf(index);
        obj.setSupport(support);
    }
    
    public void VoteDataOnDemand.setTs(Vote obj, int index) {
        Date ts = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setTs(ts);
    }
    
    public Vote VoteDataOnDemand.getSpecificVote(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Vote obj = data.get(index);
        Long id = obj.getId();
        return Vote.findVote(id);
    }
    
    public Vote VoteDataOnDemand.getRandomVote() {
        init();
        Vote obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Vote.findVote(id);
    }
    
    public boolean VoteDataOnDemand.modifyVote(Vote obj) {
        return false;
    }
    
    public void VoteDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Vote.findVoteEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Vote' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Vote>();
        for (int i = 0; i < 10; i++) {
            Vote obj = getNewTransientVote(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
