package fi.opendemocracy.web.ui;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Label;
import com.vaadin.ui.Panel;
import com.vaadin.ui.VerticalLayout;

import fi.opendemocracy.domain.Category;
import fi.opendemocracy.web.ThemeConstants;


public class CategoryEntityView extends CustomComponent {
	private AbsoluteLayout mainLayout;
	private Panel scrollPanel;
	private VerticalLayout scrollContent;
	private final Category sourceCategory;
	
	public CategoryEntityView(Category c){
		sourceCategory = c;
		setCaption(c.getName());
		setIcon(ThemeConstants.TAB_ICON_CATEGORIES);
		buildMainLayout();
	}
	
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();

		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");

		// scrollPanel
		scrollPanel = buildScrollPanel();
		mainLayout.addComponent(scrollPanel);

		return mainLayout;
	}

	private Panel buildScrollPanel() {
		// common part: create layout
		scrollPanel = new Panel();
		scrollPanel.setWidth("100.0%");
		scrollPanel.setHeight("100.0%");
		scrollPanel.setImmediate(false);

		// scrollContent
		scrollContent = buildScrollContent();
		scrollPanel.setContent(scrollContent);

		return scrollPanel;
	}

	private VerticalLayout buildScrollContent() {
		// common part: create layout
		scrollContent = new VerticalLayout();
		scrollContent.setWidth("100.0%");
		scrollContent.setHeight("-1px");
		scrollContent.setImmediate(false);
		scrollContent.setMargin(true);
		scrollContent.setSpacing(true);

		Label title = new Label("<h1>" + sourceCategory.getName() + "</h1>");
		Label description = new Label("<p>" + sourceCategory.getDescription() + "</p>");
		
		Button toggleExpertise = new Button("Claim expertise");
		
		title.setContentMode(Label.CONTENT_XHTML);
		description.setContentMode(Label.CONTENT_XHTML);

		addComponent(title);
		addComponent(description);
		addComponent(toggleExpertise);
		
		return scrollContent;
	}
	
	
}
